
########### ITEMS ###########################
GET http://localhost:5164/items

###

POST http://localhost:5164/items
Content-Type: application/json

{
  "name": "cekic",
  "description": "smash things",
  "lastModifiedDate": "2026-06-01"
}

### 


########### HOMES ###########################

GET http://localhost:5164/homes/

###

POST http://localhost:5164/homes
Content-Type: application/json

{
  "name": "Bolu",
  "description": "A cozy place to live"
}

###

PUT http://localhost:5164/homes/1
Content-Type: application/json

{
  "id": 1,
  "name": "Konya",
  "description": "HAKIM KONAKLARI BEST"
}

###
DELETE http://localhost:5164/homes/1

############## ROOMS ###########################

GET http://localhost:5164/homes/2/rooms

###

POST http://localhost:5164/homes/6/rooms
Content-Type: application/json

{
  "name": "Bedroom",
  "positionX": 10,
  "positionY": 20,
  "width": 300,
  "height": 200
}

###

PUT http://localhost:5164/homes/1/rooms/1
Content-Type: application/json

{
  "name": "buyuk Bedroom",
  "positionX": 20,
  "positionY": 30,
  "width": 320,
  "height": 220
}

###
